### ISSUE TITLE
[課題] Django チュートリアルの最終回

### ISSUE THREAD

**Issue by technicakidz** [Ayaka-Nichols/my-first-blog#13]
### 概要

チュートリアルのアプリ開発が完了している状態を目指します！

### ToDo
- [x] PRを merge しローカルの更新が完了している
- [x] ORM の章の issue に自分なりの理解を記載，レッスンで確認してもらう
- [x] ローカルでアプリが期待通り動く状態
- [x] デプロイされたアプリ(URLにアクセス)もローカルと同じように動く状態

**Comment by Ayaka-Nichols** [comment]
http://nichols.pythonanywhere.com/
