### ISSUE TITLE
[課題] 221112

### ISSUE THREAD

**Issue by technicakidz** [Ayaka-Nichols/my-first-blog#18]
### 概要

チュートリアルで作成したブログアプリをカスタマイズするフェーズ．

### ToDo
- [x] 現状のDjango girls アプリ画面(カスタマイズ対象のテンプレート)を XD 上で再現
- [x] 記載した企画設計書シートをもとにデザインカンプを作成
   - できたら，PNGファイルでエクスポート，この issue のコメントに添付
- [x] Mypage サイトの修正部分を issue にピックアップ
- [x] Mypage サイトに README を簡単に追加

**Comment by technicakidz** [comment]
もし，Mypage サイトをインターネット公開まで完了されたらそちらもURLで共有ください．
教材 https://terakoya.sejuku.net/programs/53/chapters

**Comment by Ayaka-Nichols** [comment]
### 現状のDjango girls アプリ画面(カスタマイズ対象のテンプレート)を XD 上で再現[](url)
![DjangogirlsBlog_original](https://user-images.githubusercontent.com/114463167/203321640-e99d27e4-70fc-4958-bed5-9cbaed18150c.png)

![DjangogirlsBlog_new](https://user-images.githubusercontent.com/114463167/203321773-551876ed-ebf1-4bea-80ee-0a176971d24a.png)

**Comment by Ayaka-Nichols** [comment]
### 記載した企画設計書シートをもとにデザインカンプを作成
![Web 1920 – 1](https://user-images.githubusercontent.com/114463167/203348220-e37d07c9-1947-4c4a-8d5f-157f79f8dd84.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/114463167/203348235-753821ea-f5eb-408f-b38f-a401cda48656.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/114463167/203348250-b08c1357-8538-4f7b-acf1-22b4e075ef47.png)

**Comment by Ayaka-Nichols** [comment]
> もし，Mypage サイトをインターネット公開まで完了されたらそちらもURLで共有ください． 教材 https://terakoya.sejuku.net/programs/53/chapters

こちらがURLです！
 https://ayaka-nichols.github.io/Mypage/

**Comment by technicakidz** [comment]
LGTMです！
